package eu.fbk.das.domainobject.executable.utils.BotTelegram.updateshandlers.messagging;

/**
 * Created by antbucc
 */
public enum Menu {

	START, ASKLOCATION, FROMMANUAL, DETAILS, CHOOSERESULT, FROM, TO, SELEZIONE_SERVIZIO, TIMEDEPARTURE, TRANSPORTTYPE, CALCOLAVIAGGIA, LANGUAGE, AUTOBUS, TRAINS, PARKINGS, BIKESHARINGS, ROME2RIO, ROME2RIODEST, ROME2RIORESULT, CALCOLA

}
