package eu.fbk.das.domainobject.executable.utils.BotTelegram.updateshandlers.messagging;

/**
 * Created by antbucc
 */
public enum Menu {

	START, ASKLOCATION, FROMMANUAL, DETAILS, CHOOSERESULT, FROM, TO, SELEZIONE_SERVIZIO, TIMEDEPARTURE, TRANSPORTTYPE, CALCOLAVIAGGIA, LANGUAGE, AUTOBUS, TRAINS, PARKINGS, BIKESHARINGS, ROME2RIO, ROME2RIODEST, ROME2RIORESULT, CALCOLA, REFINEFROMADDRESS, REFINETOADDRESS, BLABLACARRESULT,

	VIAGGIATRENTOSTART, VIAGGIATRENTODESTINATION,

	CALCOLAROME2RIO, CALCOLABLABLACAR, ROME2RIOAFTERCHOOSE, AFTERROME2RIO

}
